pipeline {
	agent any
	tools { nodejs "NODEJS" }

	stages {
		stage ("build") {
			steps {
				dir("Practica_4/web-page 2.0") {
					sh 'ls'
					sh 'npm install'
					sh "echo BUILD"
				}
			}
		}

		stage ("Clone") {
			steps {
				dir("Practica_4/web-page 2.0") {
					// git 'https://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@github.com/PSamuels19/SA-Practicas-1S22.git'
					sh "echo CLONE"
				}
			}
		}

		stage ("SonarQube analysis") {
			steps {
				dir("Practica_4/web-page 2.0") {
					// script {
					// 	scannerHome = tool 'SonarQube'
					// }
					sh "echo SONARQUBE ANALYSIS"
				}
			}
		}

		stage ("Test") {
			steps {
				dir("Practica_4/web-page 2.0") {
					sh "npm run test"
				}
			}
		}
		
		
		stage ("Deploy") {
			steps {
				dir("Practica_4/web-page 2.0") {
					sh 'ls'
					sh "echo DEPLOY"
				}
			}
		}
	}
}
