apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-pod
  template:
    metadata:
      name: node-pod
      labels:
        app: node-pod
    spec:
      containers:
        - name: p8-node-container
          image: macochave/sa-backend-p8
          ports:
            - containerPort: 3000
