pipeline {
	agent any
	tools {
		nodejs "NODEJS"
		git "Git 2.17.1"
	}

	stages {
		stage ("build") {
			steps {
				dir("Practica_6/web-page") {
					echo "BUILD"
					sh "npm install"
				}
			}
		}

		stage ("Clone") {
			steps {
				dir("Practica_6/web-page") {
					echo "CLONE"
					git branch: 'feature/practica6', credentialsId: '3240b950-adbc-43be-81e5-80c2ebb14e23', url: 'https://github.com/PSamuels19/SA-Practicas-1S22.git'
				}
			}
		}

		stage ("SonarQube analysis") {
			steps {
				dir("Practica_6/web-page") {
					// script {
					// 	scannerHome = tool 'SonarQube'
					// }
					echo "SONARQUBE ANALYSIS"
				}
			}
		}

		stage ("Test") {
			steps {
				dir("Practica_6/web-page") {
					echo "TEST"
					sh "npm run test"
				}
			}
		}
		
		
		stage ("Deploy") {
			steps {
				dir("Practica_6/web-page") {
					echo "DEPLOY"
				}
			}
		}
	}
}
