pipeline {
	agent any
	tools { nodejs "NODEJS" }

	stages {
		stage ("build") {
			steps {
				dir("Practica_6/web-page") {
					sh "npm install"
					echo "BUILD"
				}
			}
		}

		stage ("Clone") {
			steps {
				dir("Practica_6/web-page") {
					git branch: 'feature6', credentialsId: '3240b950-adbc-43be-81e5-80c2ebb14e23', url: 'https://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@github.com/PSamuels19/SA-Practicas-1S22.git'
					echo "CLONE"
				}
			}
		}

		stage ("SonarQube analysis") {
			steps {
				dir("Practica_6/web-page") {
					// script {
					// 	scannerHome = tool 'SonarQube'
					// }
					echo "SONARQUBE ANALYSIS"
				}
			}
		}

		stage ("Test") {
			steps {
				dir("Practica_6/web-page") {
					sh "npm run test"
				}
			}
		}
		
		
		stage ("Deploy") {
			steps {
				dir("Practica_6/web-page") {
					echo "DEPLOY"
				}
			}
		}
	}
}
